tasks:
  - name: install dependencies & compile
    init: |
      echo Installing TLPI dependencies
      sudo apt update
      sudo apt install libcap-dev libacl1-dev -y
    command: |
      echo Compiling TLPI
      make -j$(nproc)
