additionalRepositories:
  - url: https://github.com/CodersSquad/tlpi-dist.git
    checkoutLocation: tlpi

tasks:
  - name: install dependencies & compile
    before: |
      cd ../tlpi
    init: |
      echo Installing TLPI dependencies
      sudo apt update
      sudo apt install libcap-dev libacl1-dev -y
    command: |
      echo Compiling TLPI
      make -j$(nproc)
